<?php 
echo '<h2>Liste des aeroports</h2>
	<br /><a href="/aeroport/ajouter"><input type="button" value="Ajouter" /></a><br /><br />
<table class="TabAeroport">
	<tr>
		<td>Trigramme</td>
		<td>Nom</td>
		<td>Terminaux</td>
		<td>Longueur de piste</td>
	</tr>';
	foreach($this->listeAeroport as $aeroport) {
	echo'<tr>
		<td>'.$aeroport['aeroport_trigramme'].'</td>
		<td>'.$aeroport['aeroport_nom'].'</td>
		<td>'.$aeroport['aeroport_terminaux'].'</td>
		<td>'.$aeroport['aeroport_longueur_piste'].'</td>
		<td class="modifier"><a href="/aeroport/modifier/id/'.$aeroport['aeroport_trigramme'].'"><img src="../img/modifier.png" class="modifier" /></a></td>
		<td class="supprimer"><a href="/aeroport/supprimer/id/'.$aeroport['aeroport_trigramme'].'"><img src="../img/supprimer.png" class="supprimer" /></a></td>
	</tr>';
}

echo '</table>';



echo '<div class="pagination"> Page - ';
	for($i= 0; $i <= $this->nbAeroport; $i++) echo '<a href="/aeroport/index?page='.($i+1).'">'.($i+1).'</a> -';
echo '</div>';
