<h2>Liste des modèles d'avion</h2>
<br />
<table>
	<tr>
		<td>Marque du modèle</td>
		<td>Référence</td>
		<td>Distance de vol maximale</td>
	</tr>
<?php
foreach($this->listeModeles as $modele) {
?>
	<tr>
		<td><?php echo $modele['modele_marque']; ?></td>
		<td><?php echo $modele['modele_reference']; ?></td>
		<td><?php echo $modele['modele_rayon']; ?></td>
		<td><a href="/modele/modifier/id/<?php echo $modele['id_modele'];?>"><img src="../img/modifier.png" class="modifier" /></a></td>
		<td><a href="/modele/supprimer/id/<?php echo $modele['id_modele'];?>"><img src="../img/supprimer.png" class="supprimer" /></a></td>
	</tr>
<?php
}
?>
</table>