<h2>Liste du catalogue de ligne</h2>
	<a href="/ligne/ajouter"><input type="button" value="Ajouter" /></a>
<table class="Tabligne">
	<thead>
		<th>Numéro de ligne</th>
		<th>Aeroport de départ</th>
		<th>Aeroport d'arrivée</th>
		<th>Occurence</th>
	</thead>

<?php

foreach($this->listeLignes as $ligne) {
	echo'<tr>
		<td>'.$ligne['id_ligne'].'</td>
		<td>'.$ligne['trigramme_depart']. ' - '. $ligne['aeroport_depart'] .'</td>
		<td>'.$ligne['trigramme_depart']. ' - '. $ligne['aeroport_depart'] .'</td>
		<td>'.$ligne['ligne_periodicite'].'</td>
		<td class="modifier"><a href="/ligne/modifier/id/'.$ligne['id_ligne'].'"><img src="/img/modifier.png" class="modifier" /></a></td>
		<td class="supprimer"><a href="/ligne/supprimer/id/'.$ligne['id_ligne'].'"><img src="/img/supprimer.png" class="supprimer" /></a></td>
	</tr>';
}
?>
</table>

<div class="pagination">
	<p>Page - 
	<?php 
	for($i = 0; $i <= $this->nbPages; $i++) {
		echo '<a href="/ligne/index/page/'.($i+1).'">'.($i+1).'</a> -';
	}
	?>
	</p>
</div>