<?php echo $this->doctype() ?>
<html lang="fr">
	<head>
		<title>INSSET Airlines</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php  echo $this->headLink()->appendStylesheet('/css/global.css')?>
	</head>
	<body>
		<div id="page">
			<header>
				<h1>INSSET AIRLINES</h1>
			</header>
			<nav>
				<div id="menu">
					<?php echo $this->layout()->menuMaintenance; ?>
					<?php echo $this->layout()->menuDrh; ?>
					<?php echo $this->layout()->menuDirection; ?>
					<?php echo $this->layout()->menuPlanning; ?>
					<?php echo $this->layout()->menuCommercial; ?>
					<?php echo $this->layout()->menuExploitation; ?>					
				</div>
			</nav>
			<section>
				<div id="apps">
					<?php echo $this->layout()->content?>
				</div>
			</section>
			<footer>
				
			</footer>
		</div>
	</body>
</html>
