<?php echo $this->doctype() ?>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <title>INSSET Airlines</title>
  <?php echo $this->headLink()->appendStylesheet('/css/index.css') ?>
 
</head>
<body>	
<div class="body">
	<div class="page">
		<header>
			<div id="header-logo"></div>
			<div id="header-text">Bienvenue sur INSSET Airlines !</div>
		</header>
		
		<section id="container">
			<div class="form"><?php echo $this->layout()->content; ?></div>
		</section>
	</div>
</div>