<?php 
echo '<h2>Liste des Vols</h2>
	<br /><a href="/vol/ajouter"><input type="button" value="Ajouter" /></a><br /><br />
<table class="TabVol">
	<tr>
		<td>Numéro Vol</td>
		<td>Ligne</td>
		<td>Avion</td>
		<td>Pilote</td>
		<td>Copilote</td>
		<td>Départ prévu</td>
		<td>Arrivée prévue</td>
	</tr>';
	foreach($this->listeVols as $vol) {
	echo'<tr>
		<td>'.$vol['id_vol'].'</td>
		<td><a href="/ligne/view/id/'.$vol['id_ligne'].'">'.$vol['aeroport_depart'].' - '.$vol['aeroport_arrivee'].'</a></td>
		<td>'.$vol['avion_immatriculation'].'</td>
		<td><a href="/user/view/id/'.$vol['id_pilote'].'">'.$vol['id_pilote'].'</a></td>
		<td><a href="/user/view/id/'.$vol['id_copilote'].'">'.$vol['id_copilote'].'</a></td>
		<td>'.$vol['vol_depart_prevu'].'</td>
		<td>'.$vol['vol_arrivee_prevue'].'</td>
		<td class="modifier"><a href="/vol/modifier/id/'.$vol['id_vol'].'"><img src="../img/modifier.png" class="modifier" /></a></td>
		<td class="supprimer"><a href="/vol/supprimer/id/'.$vol['id_vol'].'"><img src="../img/supprimer.png" class="supprimer" /></a></td>
	</tr>';
	}

echo '</table><br /><div class="pagination"> Page - ';
	for($i= 0; $i <= $this->nbVols; $i++) echo '<a href="/vol/index?page='.($i+1).'">'.($i+1).'</a> -';
echo '</div>';